name: Run Tests
on: push

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Install
        uses: abatilo/actions-poetry@v1.5.0
        with:
            python_version: 3.8
            poetry_version: 1.0.3
            args: install

        - name: Run pytest
        uses: abatilo/actions-poetry@v1.5.0
        with:
            python_version: 3.8
            poetry_version: 1.0.3
            args: run python -m pytest --cov=tyd tests/
